### ISSUE TITLE
Checkbox Code Section Results In 'const' Error

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/react-hooks-forms-abstraction#8]
### Canvas Link

https://learning.flatironschool.com/courses/5285/assignments/172312?module_item_id=376341

### Concern

When checkbox is clicked upon using the final version of the 'Form' component for this lab, the following error is received:

TypeError: Assignment to constant variable.
handleChange
src/components/Form.js:20
  17 | 
  18 | // Use 'checked' property of checkboxes instead of value:
  19 | if (event.target.type === "checkbox") {
> 20 |   value = event.target.checked;
     | ^  21 | }
  22 | 
  23 | setFormData({

### Suggested Changes

Most likely, this needs a revision to use 'let' instead of 'const' for the checkbox based attribute, 'admin'.
![Screen Shot 2022-07-01 at 12 54 35 PM](https://user-images.githubusercontent.com/90813277/176938029-d95bb763-13d8-4621-8cca-8baf8cb20ba4.png)
![Screen Shot 2022-07-01 at 12 54 30 PM](https://user-images.githubusercontent.com/90813277/176938034-efcf393b-69e6-4ae6-8ca9-8e7bb60cdfab.png)

**Comment by AlveeM** [comment]
Hi Samuel, thanks for submitting the issue.

I haven't been able to replicate the error on my machine. The final version of the `Form` component seems to working fine on my end.

As for the usage of `const`, it's fine to use it here since you can mutate objects declared with `const` so long as you don't completely reassign a new object to the variable.

Please reach out to your coach or instructor regarding the error. They can help you debug the problem.
